# Generated by Django 4.0.4 on 2022-07-15 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.security.methods


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=modules.security.methods.get_file_path),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6aa5ff', max_length=10)),
                ('primary_trans_color', models.CharField(default='#6aa5ff77', max_length=10)),
                ('secondary_color', models.CharField(default='#4883dd', max_length=10)),
                ('base_color', models.CharField(default='#fff', max_length=10)),
                ('base_trans_color', models.CharField(default='#fff7', max_length=10)),
                ('text_color', models.CharField(default='#000', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
